### ISSUE TITLE
Request to contact

### ISSUE THREAD

**Issue by sravan953** [kelu124/un0rick#1]
Hello kelu124!

I was happy to come across this project about open-source hardware for ultrasound imaging. I am a PhD student, working on open-source hardware for MRI. I am exploring available boards and instruments for the project. I hope to get in touch with you for your inputs about some of the design decisions.
Please let me know.

**Comment by kelu124** [comment]
Hey @sravan953 , my pleasure to connect and happy to discuss. I have seen a few interesting things such as https://www.opensourceimaging.org/project/hybrid-mri%E2%80%90ultrasound-scannerless-real%E2%80%90time-imaging/ . 

Come and have a chat on our slack ?
https://join.slack.com/usdevkit/shared_invite/MTkxODU5MjU0NjI1LTE0OTY1ODgxMDEtMmYyZTliZDBlZA . Cheers!

**Comment by sravan953** [comment]
Thank you!

**Comment by sravan953** [comment]
The Slack invite seems to be broken, could you please share another invite?

**Comment by sravan953** [comment]
@kelu124 The Slack invite you shared earlier is broken, could you please share another invite?

**Comment by kelu124** [comment]
Arf thanks for raising this : that sould do the trick : https://join.slack.com/t/usdevkit/shared_invite/zt-2g501obl-z53YHyGOOMZjeCXuXzjZow

**Comment by sravan953** [comment]
Thank you!
